version: '3'
services:
  server:
    build:
      dockerfile: 'packages/server/Dockerfile'
      context: './'
    image: 'server-bank'
    environment:
      DB_HOST: '${DB_HOST}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_NAME: '${DB_NAME}'
      DB_PORT: '${DB_PORT}'
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    env_file:
      - .env
    ports:
      - '5432:5432'
  web:
    build:
      dockerfile: 'packages/web/Dockerfile'
      context: './'
    image: 'web'
    ports:
      - '3000:3000'
