version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    env_file:
      - .env
    ports:
      - '5432:5432'
